name: remote-mcp-server-demo
services:
  - name: web
    github:
      branch: main
      deploy_on_push: true
    run_command: node ./tests/0-start-server.mjs
    envs:
      - key: NODE_ENV
        value: development
    http_port: 3000
    routes:
      - path: /
